version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  api:
    container_name: docker-api
    build: ./backend
    expose:
      - 4000
    ports:
      - '4000:4000'
    links:
      - mongo
    command: sh -c 'npm install && npm run start'
  app:
    container_name: docker-app
    build: ./frontend
    expose:
      - 3000
    ports:
      - '3000:3000'
    links:
      - api
    command: sh -c 'npm install && npm run start'
