version: '3'
services:
  api:
    container_name: docker-api
    build: ./backend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
