version: "3"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: Local
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    expose:
      - "3306"
    networks:
      - app-network
  api_test_dev:
    build: ./
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - PORT=4000
    ports:
      - "4000:4000"
    working_dir: /app
networks:
  app-network:
    driver: bridge
